// CRACKER P2.3 — the power table: minimum detectable effect (MDE) vs sample size.
//
// Kills "underpowered-reported-as-null": for each symbol × horizon × subsample
// size n, the day-block bootstrap SE of the uniq_w-weighted mean drift-adjusted
// markout gives MDE = (z_{0.025} + z_{0.20})·SE ≈ 2.8·SE — the smallest true
// effect detectable at 80% power / α = 0.05 with n visits. A factor whose
// plausible effect < MDE at its available n is PRE-DECLARED untestable on this
// sample and queued for forward accumulation — it does not get a fake verdict.
//
// Pool: real structural sources (swing + hvn + lvn) — the population Phase-3
// factors will bucket. Placebos excluded. Subsampling respects day clustering:
// each bootstrap resample draws whole days (with replacement, shuffled) and
// truncates to the first n visits.
//
// Published artifact: docs/cracker-power.md (re-run as forward days accrue —
// deterministic given the data; stamp = max trading_day in the trace).
// Run: pnpm --filter @trading/aggregator exec tsx scripts/cracker_p23_power.ts
import Database from 'better-sqlite3';
import fs from 'node:fs';

const ROOT = '/Users/ravikumarbasker/trading-cockpit/data';
const DB = process.env.TRACE_DB ?? `${ROOT}/cracker-trace.db`;
const OUT = '/Users/ravikumarbasker/trading-cockpit/docs/cracker-power.md';
const SYMS = ['NQ', 'ES'];
const HORIZONS = [1, 5, 15, 30] as const;
const NS = [50, 100, 200, 500, 1000, 2000] as const;
const B = 2000;
const Z_MDE = 2.8;   // z_{α/2}=1.96 + z_{β}=0.84 (80% power, two-sided 5%)
// P0.4 attenuation: a true MINI effect appears shrunk when screened on MICRO
// delta features — divide the observable effect (or multiply the required MDE).
const ATTEN: Record<string, number> = { NQ: 0.8, ES: 0.65 };

function lcg(seed: number) { let s = seed >>> 0; return () => (s = (1664525 * s + 1013904223) >>> 0) / 2 ** 32; }

interface Row { day: string; x: number; w: number; }

function seOfMeanAtN(byDay: Map<string, Row[]>, n: number | null, seed: number): { se: number; est: number } | null {
  const days = [...byDay.keys()].sort();
  const all = days.flatMap((d) => byDay.get(d)!);
  if (n != null && all.length < n) return null;
  const wmean = (rs: Row[]) => { let sw = 0, sx = 0; for (const r of rs) { sw += r.w; sx += r.w * r.x; } return sw > 0 ? sx / sw : NaN; };
  const rnd = lcg(seed);
  const vals: number[] = [];
  for (let b = 0; b < B; b++) {
    const rows: Row[] = [];
    if (n == null) {
      for (let i = 0; i < days.length; i++) rows.push(...byDay.get(days[Math.floor(rnd() * days.length)]!)!);
    } else {
      while (rows.length < n) rows.push(...byDay.get(days[Math.floor(rnd() * days.length)]!)!);
      rows.length = n;
    }
    const v = wmean(rows);
    if (isFinite(v)) vals.push(v);
  }
  const m = vals.reduce((a, v) => a + v, 0) / vals.length;
  const se = Math.sqrt(vals.reduce((a, v) => a + (v - m) ** 2, 0) / (vals.length - 1));
  return { se, est: wmean(all) };
}

function main() {
  const db = new Database(DB, { readonly: true });
  const stamp = (db.prepare(`SELECT MAX(trading_day) d FROM visit_features`).get() as any).d;
  const lines: string[] = [];
  const say = (s: string) => { lines.push(s); console.log(s); };

  say(`# Cracker Power Table — minimum detectable effect (MDE)`);
  say(``);
  say(`> Generated by \`cracker_p23_power.ts\` · data through **${stamp}** · re-publish as forward days accrue.`);
  say(`> MDE = 2.8 × SE(day-block bootstrap, B=${B}) of the uniq_w-weighted mean drift-adjusted markout —`);
  say(`> the smallest TRUE effect (in points) detectable at 80% power / α=0.05 with n visits.`);
  say(`> **Usage rule (frozen):** a Phase-3 factor is testable at its available n only if its plausible`);
  say(`> effect ≥ MDE(n). Below that → pre-declared UNTESTABLE, queued for forward accumulation.`);
  say(`> Effects screened on the MICRO store must first be shrunk by the P0.4 attenuation`);
  say(`> (×0.8 NQ, ×0.65 ES) before comparison — equivalently use the "micro-screen MDE" columns.`);
  say(``);

  for (const sym of SYMS) {
    const rows = (db.prepare(`
      SELECT vf.trading_day day, vo.uniq_w w, dc.drift_pt_min drift,
        vo.mo_1m, vo.mo_5m, vo.mo_15m, vo.mo_30m
      FROM visit_features vf
      JOIN visit_outcomes vo ON vo.level_id = vf.level_id AND vo.close_ts = vf.close_ts AND vo.symbol = vf.symbol
      JOIN day_context dc ON dc.symbol = vf.symbol AND dc.trading_day = vf.trading_day
      WHERE vf.symbol = ? AND vf.source IN ('swing','hvn','lvn')`).all(sym) as any[]);
    const nDays = new Set(rows.map((r) => r.day)).size;
    say(`## ${sym} — pool: swing+hvn+lvn visits, n=${rows.length} across ${nDays} days`);
    say(``);
    say(`| horizon | ${NS.map((n) => `MDE@n=${n}`).join(' | ')} | MDE@full(${rows.length}) | micro-screen MDE@full |`);
    say(`|---|${NS.map(() => '---').join('|')}|---|---|`);
    for (const h of HORIZONS) {
      const col = { 1: 'mo_1m', 5: 'mo_5m', 15: 'mo_15m', 30: 'mo_30m' }[h]!;
      const pool: Row[] = rows.filter((r) => r[col] != null)
        .map((r) => ({ day: r.day, x: r[col] - (r.drift ?? 0) * h, w: r.w ?? 1 }));
      const byDay = new Map<string, Row[]>();
      for (const r of pool) { if (!byDay.has(r.day)) byDay.set(r.day, []); byDay.get(r.day)!.push(r); }
      const cells: string[] = [];
      for (const n of NS) {
        const r = seOfMeanAtN(byDay, n, 1000 + h * 10 + n + (sym === 'ES' ? 7 : 0));
        cells.push(r ? `${(Z_MDE * r.se).toFixed(2)}pt` : '—');
      }
      const full = seOfMeanAtN(byDay, null, 2000 + h + (sym === 'ES' ? 7 : 0))!;
      const fullMde = Z_MDE * full.se;
      cells.push(`${fullMde.toFixed(2)}pt`);
      cells.push(`${(fullMde / ATTEN[sym]!).toFixed(2)}pt`);
      say(`| m̃(${h}m) | ${cells.join(' | ')} |`);
    }
    say(``);
  }

  say(`### Reading it`);
  say(``);
  say(`- Row = markout horizon; column = visits available to the factor bucket being tested.`);
  say(`- Example: a factor bucket with 200 visits can only prove effects ≥ the @n=200 cell; a`);
  say(`  plausible-but-smaller effect must WAIT for more days rather than be declared null.`);
  say(`- The "micro-screen" column is the bar for effects measured on micro data but claimed`);
  say(`  for the mini market (P0.4 attenuation ×${ATTEN['NQ']} NQ / ×${ATTEN['ES']} ES).`);
  say(`- Companion baselines (same data, cracker_p21_selftest.ts): placebo hold-rate band and the`);
  say(`  visit-mechanics continuation curve — Phase-3 comparisons are VISITS-vs-VISITS against these,`);
  say(`  never vs random-time or analytic nulls.`);

  fs.writeFileSync(OUT, lines.join('\n') + '\n');
  console.log(`\nwritten → ${OUT}`);
  db.close();
}
main();
